name: action test

on: [push]

jobs:
  cloner:
    runs-on: self-hosted
    steps:
    - run: echo "we are starting our work because of ${{ github.event_name }} and this runner is on ${{ runner.os }}"
    - run: echo "work is coming from ${{ github.repository }} and branch ${{ github.ref }}"
    - name: clone the repository
      uses: actions/checkout@v3
    - name: giving a report to the pipeline
      run: |
        ls ${{ github.workspace }}
        pwd
        whoami
    - run: echo "job is done and we are at ${{ job.status }} status"
